### PR TITLE
added colors for PGSB genes

### PR DESCRIPTION
**Pull request by gnaamati**
Adding colours for 10+ genes

### CODE REVIEW

**Comment by ens-ds23** [comment]
Do you have an example page/image/region where I can do a before and after on this, @gnaamati ?

**Comment by gnaamati** [comment]
hi Dan, here is an example:
http://wp-np3-86.ebi.ac.uk:8003/Triticum_aestivum_lancer/Location/View?db=core;r=3A:206765383-206768765

As you can see all is other.

This is how it looks on my sandbox (also with low confidence which will be added later):
http://ves-hx2-77:6097/Triticum_aestivum_lancer/Location/View?db=core;r=3A:206765383-206768765

**Comment by ens-ds23** [comment]
This looks uncontroversial/low-impact and runs in your sandbox so I'll do the fast-track thing of merging it in and pulling to staging first, in a sec, and then we can double-check after.

**Comment by ens-ds23** [comment]
Updated and restarted. Verified colour change.

**Comment by gnaamati** [comment]
Looks good, thanks!
Will recheck this when the low confidence genes get loaded (after otherfeatures handover) and there might be a few colours I need to add tweak later.
Thanks for fixing this :)

**Pull request merged**
