### PR TITLE
adding color codes for gff3 high and low conf

### PR DESCRIPTION
**Pull request by shradhaebi**
Added two color codes for high and low confident genes.

### CODE REVIEW

**Comment by ridwanamo** [comment]
@shradhaebi can you please add reviewers?

**Comment by gnaamati** [comment]
Hi @ridwanamo, we've never been asked for reviewers in the past as this is a fairly straightforward color code add. Do you know what changed and who would be a reviewer? I'm also happy to review if that would work?

**Comment by ridwanamo** [comment]
sorry my mistake then, it was during our code review that this got picked up and we weren't sure what to do with it and the first thing that we normally check in a PR is the branch and then the reviewers. 

But if it is a simple change, we should be fine to merge it. We can probably have someone in the webteam to review it.

**Comment by jyothishnt** [comment]
Merging this. Please check sandbox to confirm.

**Comment by gnaamati** [comment]
Thanks, do you know what needs to be done so we can see this in staging?

**Pull request merged**
