### PR TITLE
added colours for new wheat site

### PR DESCRIPTION
**Pull request by gnaamati**
I added colours for the new wheat site. Please review.

Thanks
Guy

### CODE REVIEW

**Comment by dbolser-ebi** [comment]
Nice!

**Comment by nicklangridge** [comment]
Is this for EG32?

**Comment by pkersey** [comment]
what should I be reviewing?
thanks
P.
---
Dr. Paul Kersey
Team Leader, Non-vertebrate Genomics
Room A3134
EMBL-The European Bioinformatics Institute
Wellcome Genome Campus
Hinxton 
Cambridgeshire
CB10 1SD
United Kingdom
Tel: 44 (0) 1223-494602 Fax: 44 (0) 1223-494468

**Comment by gnaamati** [comment]
Nick, this is for EG32.
Paul, the review statement is for the web team. 
They need to look at the diff of the conf file which I committed before it is added to the main branch (just to make sure the additions are valid)

**Pull request merged**
